name: CI / CD

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Run the tests and generate coverage report
        run: yarn test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Deploy
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          yarn deploy
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
